#!/usr/bin/env bash

# Base
if ! source "${BASH_SOURCE%/*}/../base"; then
  exit 1
fi

# Отправляем POST-запрос для регистрации пользователя
res=$(curl -s -X POST "$api_url/$register_url" \
  -H "Content-Type: application/json" \
  -d \
  '{
    "email": "'"$user_email"'",
    "password": "'"$user_password"'",
    "first_name": "Oleg",
    "last_name": "Safronov",
    "birthday": "18-10-2004",
    "gender": "Male"
  }'
)

# Проверяем, успешна ли регистрация
if ! echo "$res" | jq -re '.email' 1>/dev/null 2>&1; then
    echo "$res" | jq
    exit 1
fi

echo "$res" | jq
