#!/usr/bin/env bash

# Base
if ! source "${BASH_SOURCE%/*}/../base"; then
  exit 1
fi

# Отправляем POST-запрос для регистрации пользователя
req=$(curl -s -X POST "$api_url/$register_url" \
  -H "Content-Type: application/json" \
  -d \
  '{
    "email": "'"$user_email"'",
    "password": "'"$user_password"'",
    "firstname": "Oleg",
    "lastname": "Safronov",
    "birthday": "18-10-2004",
    "gender": "Male"
  }'
)

# Проверяем, успешна ли регистрация
if ! echo "$req" | jq -r '.token' 1>/dev/null 2>&1; then
    echo "$req" | jq
    exit 1
fi

# Отправляем POST-запрос для авторизации пользователя
req=$(curl -s -X POST "$api_url/$login_url" \
  -H "Content-Type: application/json" \
  -d \
  '{
    "email": "'"$user_email"'",
    "password": "'"$user_password"'"
  }'
)

# Проверяем, успешна ли авторизация
if ! echo "$req" | jq -r '.token' 1>/dev/null 2>&1; then
    echo "$req" | jq
    exit 1
fi

echo "$req" | jq
