---
version: '3.8'
name: backend-dev

services:
  web:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
