version: '3.8'
name: backend

services:
  web:
    image: ghcr.io/zlp-finpd2023-2/backend:dev
    command: ./app app:serve
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env.prod
      - .env.prod.db
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
