---
version: '3.9'
name: backend

services:
  web:
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    command: ./finapp app:serve
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - path: .env
        required: true
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
