---
version: '3.9'
name: backend

services:
  web:
    env_file:
      - path: .prod.env
        required: true
      - path: .prod.db.env
        required: true
    image: ghcr.io/zlp-finpd2023-2/backend:dev
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile.prod
    command: ./finapp app:serve
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - path: .prod.db.env
        required: true
