---
version: '3.8'
name: backend

services:
  web:
    env_file:
      - .env.prod
      - .env.prod.db
    image: ghcr.io/zlp-finpd2023-2/backend:dev
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile.prod
    command: ./finapp app:serve
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
