---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - name: "app"
        image: "{{ .Values.app.imageName }}"
        imagePullPolicy: Always
        command: 
          - "./finapp"
          - "app:serve"
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
        envFrom:
          - configMapRef:
              name: "{{ .Chart.Name }}"
