#!/usr/bin/env bash

api_url=${API_URL:-"http://localhost:8080/api/v1"}
health_url=${HEALTH_URL:-"readiness"}

export register_url="auth/register"
export login_url="auth/login"
export goal_url="goal"
export budget_url="budget"
export trx_url="trx"

# Проверка доступности сервера
if ! curl "$api_url/$health_url" 1>/dev/null 2>&1; then
  echo "Server not available" 1>&2
  exit 1;
fi

# Генерация данных пользователя
export user_password=${USER_PASSWORD:-"password${RANDOM}"}
export user_email=${USER_EMAIL:-"user${RANDOM}@example.com"}

# Переменные
export date_from="10-03-2024"
export date_to="13-03-2024"
